apiVersion: v1
kind: Service
metadata:
  name: myservicelast
spec:
  ports:
  - port: 8080
  selector:
    app: myservicelast
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myservicelast
spec:
  selector:
    matchLabels:
      app: myservicelast
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myservicelast
    spec:
      containers:
      - image: danielepalaia/go-list
        name: myservicelast 
        env:
        ports:
        - containerPort: 8080 
          name: myservicelast
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
                claimName: mysql-pv-claim2
