apiVersion: v1
kind: Service
metadata:
  name: myservicelast
spec:
  type: NodePort 
  ports:
  - port: 8080 
    nodePort: 30180
  selector:
    app: myservicelast
  clusterIP: 10.96.2.5 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myservicelast
spec:
  selector:
    matchLabels:
      app: myservicelast
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myservicelast
    spec:
      containers:
      - image: danielepalaia/go-list
        name: myservicelast 
        env:
        ports:
        - containerPort: 8080 
          name: myservicelast
